### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ikiziki** [marukoapp/Maruko#1]
When working on smaller screens the developer friendly keys above the keyboard are helpful but 3 rows of them take up more real estate than I would like. 

Carat placement could use some work. The carat actively avoids being placed inside existing code by tap and must be manipulated with touch and drag. This gets the carat where you need it but when you tap to access "copy/paste" the carat jumps away from where you need it. This results in a loop of fighting with the editor to get the carat in place. 

Adjustable font in the editor. Both font type and size would be appreciated.

**Comment by marukoapp** [comment]
Thank you for the feedback. Yes, Maruko includes many bold ideas. The concept of a 3-line additional keyboard stems from the inefficiency of switching inputs frequently, but it may also present another issue: limited screen space. Perhaps I can provide options for who can take the stage.

The idea of moving the caret was previously considered: sliding on the additional keyboard to position the cursor, but it wasn't smooth enough, so this feature wasn't implemented, but it's not a big issue. Copy/paste could possibly be achieved through additional buttons.

Regarding fonts, yes, the editor should have more options.
