### ISSUE TITLE
Clear logs?

### ISSUE THREAD

**Issue by dlasky** [marukoapp/Maruko#2]
It would be awesome if there was a way to clear the logs after runs.

**Comment by marukoapp** [comment]
This feature will be available in the next version 1.4.

**Comment by dlasky** [comment]
Amazing thank you!!

**Comment by dlasky** [comment]
Sorry for the bump. What is the ETA for 1.4?

**Comment by marukoapp** [comment]
Hi, Dan

I apologize for keeping you waiting as I have been busy with work. Version
1.4 will be released within a week and will prioritize fixing this issue.

Best Regards,
SHU

Dan ***@***.***> 于2024年8月15日周四 04:52写道：

**Comment by dlasky** [comment]
No worries! I totally understand (as i am often in the same situation myself)

Thank you!

**Comment by dlasky** [comment]
Thank you works great!!
